[workspace]
members = [
    'sixtyfps_runtime/corelib',
    'sixtyfps_runtime/corelib_macros',
    'sixtyfps_runtime/interpreter',
    'sixtyfps_runtime/rendering_backends/gl',
    'sixtyfps_runtime/rendering_backends/qt',
    'sixtyfps_runtime/rendering_backends/default',
    'sixtyfps_runtime/rendering_backends/testing',
    'sixtyfps_compiler',
    'sixtyfps_compiler/parser_test_macro',
 #   'api/sixtyfps-rs',
 #   'api/sixtyfps-rs/sixtyfps-macros',
 #   'api/sixtyfps-rs/sixtyfps-build',
 #   'api/sixtyfps-cpp',
 #   'api/sixtyfps-node/native',
    'api/sixtyfps-wasm-interpreter',
  #  'tools/compiler',
    'tools/fmt',
    'tools/lsp',
    'tools/syntax_updater',
    'tools/viewer',
  #  'examples/gallery',
  #  'examples/printerdemo/rust',
  #  'examples/printerdemo_old/rust',
  #  'examples/todo/rust',
  #  'examples/slide_puzzle',
  #  'examples/7gui',
  #  'examples/memory',
    'helper_crates/const-field-offset',
    'helper_crates/vtable',
    'helper_crates/vtable/macro',
    'xtask',
   # 'tests/doctests',
   # 'tests/driver/driverlib',
   # 'tests/driver/rust',
   # 'tests/driver/cpp',
   # 'tests/driver/nodejs',
   # 'tests/driver/interpreter',
]

default-members = [
    'sixtyfps_runtime/corelib',
    'sixtyfps_runtime/interpreter',
    'sixtyfps_runtime/rendering_backends/gl',
    'sixtyfps_runtime/rendering_backends/qt',
    'sixtyfps_runtime/rendering_backends/default',
  #  'sixtyfps_compiler',
  #  'api/sixtyfps-rs',
  #  'api/sixtyfps-rs/sixtyfps-build',
  #  'api/sixtyfps-node/native',
  #  'tools/compiler',
    'tools/fmt',
    'tools/lsp',
    'tools/syntax_updater',
    'tools/viewer',
  #  'examples/gallery',
  #  'examples/printerdemo/rust',
  #  'examples/printerdemo_old/rust',
  #  'examples/todo/rust',
  #  'examples/slide_puzzle',
  #  'examples/memory',
  #  'tests/doctests',
  #  'tests/driver/rust',
  #  'tests/driver/nodejs',
  #  'tests/driver/interpreter',
]

resolver = "2"

# Pull in https://github.com/femtovg/femtovg/commit/14424393276f23a5105192fdb179db2a03e42d0d to
# shrink our (wasm) binaries (post 0.1.3)
[patch.crates-io]
femtovg = { git = "https://github.com/femtovg/femtovg", rev = "14424393276f23a5105192fdb179db2a03e42d0d" }

[profile.release]
lto = true
panic = "abort"

[profile.dev]
panic = "abort"
