[package]
name = "sixtyfps-viewer"
version = "0.0.6"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Viewer binary for SixtyFPS"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[dependencies]
sixtyfps-interpreter = { version = "=0.0.6", path = "../../sixtyfps_runtime/interpreter", features = ["display-diagnostics"] }
sixtyfps = { version = "=0.0.6", path="../../api/sixtyfps-rs" }
vtable = { version = "0.1", path="../../helper_crates/vtable" }
structopt = "0.3.14"
codemap-diagnostic = "0.1.1"
codemap = "0.1"
spin_on = "0.1"
notify = "4.0.15"


[[bin]]
name = "sixtyfps-viewer"
path = "main.rs"
