[package]
name = "sixtyfps-lsp"
version = "0.0.6"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "SixtyFPS LSP server"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[package.metadata.bundle]
name = "SixtyFPS Live Preview"
icon = ["../../vscode_extension/extension-logo.png"]

[[bin]]
name = "sixtyfps-lsp"
path = "main.rs"

[dependencies]
sixtyfps-compilerlib = { version = "=0.0.6", path = "../../sixtyfps_compiler"}
sixtyfps-interpreter = { version = "=0.0.6", path = "../../sixtyfps_runtime/interpreter"}
sixtyfps-corelib = { version = "=0.0.6", path = "../../sixtyfps_runtime/corelib"}
sixtyfps-rendering-backend-default = { version = "=0.0.6", path="../../sixtyfps_runtime/rendering_backends/default" }
lsp-server = "0.5"
lsp-types = "0.83" # must match the version used by lsp-server
crossbeam-channel = "0.5"  # must match the version used by lsp-server
serde_json = "1.0.60"
serde = "1.0.118"
spin_on = "0.1"
once_cell = "1"
dunce = "1.0.1"